Repository OOL-Project-2025/OOL_Project, pull requests merged in 2025-03, with the labels that each got.

#3 #2/feat create chart table
  .github/pull_request_template.md
  src/main/java/com/OOL/oolfinance/entity/chart/Chart.java
Labels: feat, docs

#6 #5/feat signup
  build.gradle
  src/main/java/com/OOL/oolfinance/config/SecurityConfig.java
  src/main/java/com/OOL/oolfinance/controller/HomeController.java
  src/main/java/com/OOL/oolfinance/controller/MemberController.java
  src/main/java/com/OOL/oolfinance/dto/MemberDTO.java
  src/main/java/com/OOL/oolfinance/entity/member/Member.java
  src/main/java/com/OOL/oolfinance/repository/member/MemberRepository.java
  src/main/java/com/OOL/oolfinance/service/member/MemberService.java
  src/main/resources/static/index.html
  src/main/resources/static/save.html
Labels: feat, chore

#7 마이페이지 관련 내용
  build.gradle
  src/main/java/com/OOL/oolfinance/config/QueryDSLConfig.java
  src/main/java/com/OOL/oolfinance/controller/MemberRestController.java
  src/main/java/com/OOL/oolfinance/entity/chart/Chart.java
  src/main/java/com/OOL/oolfinance/entity/member/Member.java
  src/main/java/com/OOL/oolfinance/enums/MemberStatus.java
  src/main/java/com/OOL/oolfinance/repository/member/MemberCustomRepository.java
  src/main/java/com/OOL/oolfinance/repository/member/MemberCustomRepositoryImpl.java
  src/main/java/com/OOL/oolfinance/repository/member/MemberRepository.java
  src/main/java/com/OOL/oolfinance/service/member/MemberService.java
  src/main/java/com/OOL/oolfinance/service/member/MemberServiceImpl.java
  src/main/resources/application-dev.yml
Labels: feat, rename
